Added  folder structure
navadhiti/tell-portal pull request #1
Opened 2023-11-02 07:32 UTC by palani-ND

Created folder structure , using vite react js

2023-11-06 08:48 UTC, arunjose1995 requested changes
There are some more root stuffs missing @palani-ND . I would recommend add those and keep them empty. Add the `.DS_Store` in the ignore file

2023-11-06 08:48 UTC, arunjose1995 commented on README.md
> +- [@vitejs/plugin-react-swc](https://github.com/vitejs/vite-plugin-react-swc) uses [SWC](https://swc.rs/) for Fast Refresh
Must be more descriptive and should hold the information about what the application is about,  how to run the application, how to deploy if at all is has to be, any environment variables to be updated or created. This should simply be as separate issue for all of us to collaboratively update. For now remove the contents in here and keep the default value you had earlier.

2023-11-06 08:48 UTC, arunjose1995 commented on package.json
> +}
Do not use `^` symbols in the dependencies or dev ones. Just use the package version as is. This is to avoid people overwriting the package-lock file when ever they are doing a `npm i`. We will bring in a add-on that will keep all the packages up-to-date

2023-11-06 08:48 UTC, arunjose1995 commented on src/App.jsx
> +    </>
```suggestion
      <Router />
```

2023-11-06 08:48 UTC, arunjose1995 commented on src/App.jsx
> +    </>
Only have required element, never use fragments unless multiple child elements are to be loaded

2023-11-06 08:48 UTC, arunjose1995 commented on src/Router.jsx
> +import React from "react";
keep these kind of  file names in lower case. Just a standard discrimination between component names and other files

2023-11-06 08:48 UTC, arunjose1995 commented on src/Router.jsx
> +  return <div>Tell-portal</div>;
Here you should prefer using react fragment `<></>` rather than `<div></div>`

2023-11-06 08:49 UTC, arunjose1995 commented
All the mentioned folders are not present in the PR as they appear to have no files in them.

2023-11-06 16:54 UTC, palani-ND commented on README.md
> +- [@vitejs/plugin-react-swc](https://github.com/vitejs/vite-plugin-react-swc) uses [SWC](https://swc.rs/) for Fast Refresh
For now i kept it empty

2023-11-06 16:54 UTC, palani-ND commented on package.json
> +}
removed

2023-11-06 16:55 UTC, palani-ND commented on src/App.jsx
> +    </>
Done the changes

2023-11-06 16:55 UTC, palani-ND commented on src/Router.jsx
> +import React from "react";
Done the Changes

2023-11-06 16:55 UTC, palani-ND commented on src/Router.jsx
> +  return <div>Tell-portal</div>;
Completed

2023-11-06 16:57 UTC, palani-ND commented
have made the changes and added husky, prettier and eslint

2023-11-07 04:41 UTC, arunjose1995 commented
<img width="906" alt="Screenshot 2023-11-07 at 10 09 56 AM" src="https://github.com/navadhiti/tell-portal/assets/26113143/564018b1-46f4-4582-a134-15fd3c18cdf2">

@palani-ND strongly recommended these kind of commits are not added in the PR's. I would recommend you to re-create a PR or have force pushes made to this PR removing all the other commits

2023-11-07 04:44 UTC, arunjose1995 requested changes
To begin with rest all looks good. Remove the `.DS_Store` file from the files list

2023-11-07 06:26 UTC, palani-ND commented
Bringing this down due to unrelated commit history. Reference PR #2 which holds valid history.

2023-11-07 06:26 UTC, closed without merging